config/routes.rb
Rails.application.routes.draw do

  get 'messages/new'

  get 'messages/create'

  get 'tables/show'
  get 'tables/create' => 'tables#new'

  root      'static_pages#home'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get       'signup' =>  'users#new'
  get       'login'   => 'sessions#new'
  post      'login'   => 'sessions#create'
  delete    'logout'  => 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :microposts do
    resources :comments, only: [:new, :create]
  end

  resources :comments

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]
  resources :tables do            
    resources :messages,            only: [:new, :create]
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if logged_in?
  		redirect_to current_user
  	end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="home-background-image"></div>
<div class="home-signin col-md-5">
<div class="row">
	<div class="col-md-12">
		<%= form_for(:session, url: login_path) do |f| %>

		<%= f.label :email %>
		<%= f.email_field :email, class: 'form-control' %>

		<%= f.label :password %>
		<%= link_to "(forgot password)", new_password_reset_path %>
		<%= f.password_field :password, class: 'form-control' %>

		<%= f.label :remember_me, class: "checkbox inline" do %>
			<%= f.check_box :remember_me %>
			<span>Remember me on this computer</span>
		<% end %>

		<%= f.submit "Log in", class: "btn btn-primary" %>
		<% end %>

		<p>New user? <%= link_to "Sign up now!", signup_path %></p>
	</div>
</div>
</div>