config/routes.rb
Rails.application.routes.draw do

  get 'messages/new'

  get 'messages/create'

  get 'tables/show'
  get 'tables/create' => 'tables#new'

  root      'static_pages#home'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get       'signup' =>  'users#new'
  get       'login'   => 'sessions#new'
  post      'login'   => 'sessions#create'
  delete    'logout'  => 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :microposts do
    resources :comments, only: [:new, :create]
  end

  resources :comments

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]
  resources :tables do            
    resources :messages,            only: [:new, :create]
  end

end

app/controllers/tables_controller.rb
class TablesController < ApplicationController

  has_scope :cuisine
  has_scope :keywords

  def create
    @table = Table.new(table_params)
    @table.user = current_user
    @table.cuisine = params[:cuisine]
    if @table.save
      redirect_to @table
    else
      render 'new'
    end
  end

	def search
	end

	def index
    @tables = apply_scopes(Table).all.paginate(page: params[:page], per_page: 48)
    
    respond_to do |format|
      format.html
      format.js
    end
	end

  def new
    @table = Table.new
  end

  def destroy
    Table.find(params[:id]).destroy
    flash[:success] = "Table sucessfully cleaned"
    redirect_to root_url
  end

  def tables

  end

  def show
  	@table = Table.find(params[:id])
    @user = User.find(@table.user.id)
    @message = Message.new
    @messages = Message.order('created_at DESC')
  end

  private

    def table_params
      params.require(:table).permit(:title, :cuisine)
    end

end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/tables/_table.html.erb
<div class="col-sm-3">      	
	<div class="table">
		<div class="table-image">
			<%= image_tag table.user.avatar.url if table.user.avatar? %>
		</div>
		<h4><%= link_to truncate(table.title, :length => 24), table %></h4>
		<p>
			Cuisine: <%= table.cuisine %><br />
			User: <%= table.user.username %>
		</p>
	</div> 
</div>

app/views/tables/index.html.erb
<% provide(:title, 'Search for a table') %>
<%= render 'shared/arrow_scroll' %>

<% if logged_in? %>
	<div class="row" id="top">
		<%= link_to "Create a table!", tables_create_path, class: 'btn btn-success' %>
	</div>
<% end %>

<h1>Search for a table</h1>

<div class="row">
	<div class="col-md-6">
		<%= form_tag tables_path, :method => 'get' do %>
			<%= label_tag :keywords %>
			<%= text_field_tag :keywords, nil, class: 'form-control' %>

			<%= label_tag :cuisine %>
			<%= select_tag :cuisine, options_for_select(Table.uniq.pluck(:cuisine).sort), { include_blank: true,
				class: 'form-control' } %>

			<%= submit_tag "Search", :name => nil, class: 'btn btn-primary' %>
		<% end %>
	</div>
</div>

<div id="table_count">
	<p><%= @tables.count %> tables found!</p>
</div>

<div class="row" id="table-list">
	<%= render @tables %>
</div>

<div id="infinite-scrolling">
  <%= will_paginate %>
</div>

app/views/tables/index.js.erb
$(document).on('scroll', function() {

	if ($(window).scrollTop() > 100 ) {
	    $('#top-link-block').removeClass('hidden').affix({
	        // how far to scroll down before link "slides" into view
	        offset: {top:500}
	    });
	}});

$('#table-list').append('<%= j render @tables %>');
<% if @tables.next_page %>
	$('.pagination').replaceWith('<%= j will_paginate @tables %>');
<% else %>
	$(window).off('scroll');
	$('.pagination').remove();
<% end %>

app/views/tables/new.html.erb
<% provide(:title, "Create a table") %>

<h3>Create a table</h3>

<div class="row">
	<div class="col-md-6">
		<%= form_for(@table) do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
		<%= f.label :title %>
		<%= f.text_field :title, class: 'form-control' %>

		<%= f.label :cuisine %>
		<%= select_tag :cuisine , options_for_select(Table.uniq.pluck(:cuisine).sort), { include_blank: true, 
			class: 'form-control' } %>		  

		<%= f.submit "Create my table", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/tables/search.html.erb
<% provide(:title, 'Search for a table') %>
<h1>Search for a table</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
		<% form_for @search do |f| %>
	    <%= f.label :cuisine %><br />
	    <%= f.collection_select :table_id, Table.all, :id, :cuisine, :include_blank => true %>

	    <%= f.label :region %><br />
	    <%= f.collection_select :table_id, Table.all, :id, :region, :include_blank => true %>

	  	<%= f.submit "Find a table!"%>
		<% end %>
  </div>
</div>

<% form_tag tables_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

app/views/tables/show.html.erb
<% provide(:title, @table.title) %>

<%= image_tag @user.avatar.url if @user.avatar? %>
<h4><%= @user.username %></h4>

<%= @table.title %><br />
<%= @table.cuisine %><br />

<% if @table.user == current_user %>
	<%= link_to "Clean up table", @table, method: :delete, data: { confirm: "You sure?" }, 
			class: 'btn btn-danger' %>
<% else %>
	<%= link_to "Leave table", tables_path, class: 'btn btn-primary' %> 
<% end %>

<%= render 'messages/form' %>
  <div class="panel panel-default" id="table_<%= @table.id %>_messages">
    <div class="panel-body">
      <ul class="media-list">
        <%= render @table.messages %>
      </ul>
    </div>
  </div>

  <%= subscribe_to table_path(@table) %>